app:
  name: "PatraSaar"
  version: "1.0.0"
  environment: "development"

server:
  host: "localhost"
  port: 8080
  read_timeout: "30s"
  write_timeout: "30s"
  idle_timeout: "60s"

database:
  host: "localhost"
  port: 5432
  name: "patrasaar"
  user: "postgres"
  password: "postgres"
  ssl_mode: "disable"
  max_connections: 25
  max_idle_connections: 5

redis:
  host: "localhost"
  port: 6379
  password: ""
  db: 0

file_processing:
  max_file_size_mb: 50
  max_pdf_pages: 100
  allowed_extensions: [".txt", ".pdf", ".docx"]
  upload_timeout: "300s"

ai_service:
  endpoint: "http://localhost:8000"
  timeout: "120s"
  max_retries: 3
  rate_limit_per_minute: 60

security:
  cors_origins: ["http://localhost:3000"]
  rate_limit_requests_per_minute: 100
  max_request_size_mb: 60